### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by xuebiao1999** [cloudeepth/guess-number#4]
error: invalid active developer path

**Comment by Lxinglei** [comment]
Your xcode is not working normal，run this command to resolve：
`/usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
`

**Comment by Lxinglei** [comment]
@huyashuo @z1804045 你俩帮彪哥看看！

**Comment by Lxinglei** [comment]
@gaotong6434 你开完会了没有！

**Comment by z1804045** [comment]
@xuebiao1999  弄好了吧
